---
# vars file for deploy_system

username: ubuntu 
user_crypt_password: $1$xyz$YtULyRIz/nn28hEh011CG/

debug: True
local_settings: 'settings.py'

# set empty string if not used
requirements: 'requirements.txt' 

user_homedir: "/home/{{ username }}"


mysql_root_user: "root"   # root mysql user
mysql_root_password: "root"


# mysql database for current project
mysql_database: "django-rest-db"

# mysql user for current project
mysql_user: "ubuntu"

# mysql user password for current project
mysql_user_password: "ubuntu" 
